<script lang="ts">
  import { onMount } from 'svelte';
  import { settingsStore } from '$stores/settings.svelte';
  onMount(() => settingsStore.loadSettings());
  function importFile(event: Event) { const file = (event.currentTarget as HTMLInputElement).files?.[0]; if (file) settingsStore.importData(file); }
  async function clearData() { if (confirm('Clear all saved progress, recordings, and settings on this device?')) await settingsStore.clearAllData(); }
</script>

<svelte:head><title>Settings · Happy Study 3D</title></svelte:head>

<div class="settings">
  <section class="hero"><p class="eyebrow">YOUR STUDY SPACE</p><h1>Make it yours.</h1><p>Set up an environment that keeps you focused, comfortable, and ready to return tomorrow.</p><div class="status"><span class:active={settingsStore.threeDEnabled}>3D {settingsStore.threeDEnabled ? 'on' : 'off'}</span><span class:active={settingsStore.reducedMotion}>Focus mode {settingsStore.reducedMotion ? 'on' : 'off'}</span><span>Saved on this device</span></div></section>
  <div class="grid"><section class="card"><p class="eyebrow">EXPERIENCE</p><h2>Focus & comfort</h2><div class="setting"><div><strong>3D learning world</strong><span>Show animated Three.js study scenes.</span></div><button class:active={settingsStore.threeDEnabled} onclick={() => settingsStore.toggle3D()} aria-label="Toggle 3D scenes"><i></i></button></div><div class="setting"><div><strong>Reduced motion</strong><span>Limit animation when you prefer a calmer screen.</span></div><button class:active={settingsStore.reducedMotion} onclick={() => settingsStore.toggleReducedMotion()} aria-label="Toggle reduced motion"><i></i></button></div><div class="setting"><div><strong>Sound effects</strong><span>Play feedback sounds for actions and milestones.</span></div><button class:active={settingsStore.soundEnabled} onclick={() => settingsStore.toggleSound()} aria-label="Toggle sound effects"><i></i></button></div></section>
  <section class="card"><p class="eyebrow">STUDY RHYTHM</p><h2>Stay consistent</h2><div class="setting"><div><strong>Study reminders</strong><span>Get a daily reminder after enabling notifications.</span></div><button class:active={settingsStore.studyReminders} onclick={() => settingsStore.toggleStudyReminders()} aria-label="Toggle study reminders"><i></i></button></div><div class="setting"><div><strong>Notifications</strong><span>Allow browser reminders from Happy Study.</span></div><button class:active={settingsStore.notificationsEnabled} onclick={() => settingsStore.toggleNotifications()} aria-label="Toggle notifications"><i></i></button></div><div class="choices"><strong>Reading size</strong><div>{#each ['small','medium','large'] as size}<button class:chosen={settingsStore.fontSize === size} onclick={() => settingsStore.setFontSize(size as 'small' | 'medium' | 'large')}>{size}</button>{/each}</div></div></section>
  <section class="card data"><p class="eyebrow">YOUR DATA</p><h2>Keep control</h2><p>Your progress and recordings are stored in this browser. Export a backup before clearing your data or moving devices.</p><div class="data-actions"><button onclick={() => settingsStore.exportData()}>Export backup</button><label>Import backup<input type="file" accept="application/json" onchange={importFile} /></label><button class="danger" onclick={clearData}>Clear device data</button></div></section>
  <section class="card help"><p class="eyebrow">NEED A STUDY SYSTEM?</p><h2>Use Happy Study for review; use a notes app to own the knowledge.</h2><p>For each topic, capture your key terms, one worked example, and the mistake you want to avoid. Obsidian, OneNote, and Google Keep all work well.</p><a href="/freecodecamp">Continue coding with FreeCodeCamp →</a></section></div>
</div>

<style>
  .settings{display:grid;gap:1.2rem}.hero{padding:clamp(2rem,6vw,4.5rem);border-radius:30px;background:radial-gradient(circle at 80% 20%,rgba(124,58,237,.5),transparent 28rem),linear-gradient(130deg,#111827,#172554);border:1px solid rgba(167,139,250,.25)}.eyebrow{font-size:.7rem;letter-spacing:.14em;font-weight:800;color:#c4b5fd;margin:0 0 .7rem}.hero h1{font-size:clamp(3rem,7vw,5.5rem);letter-spacing:-.07em;line-height:.9;margin:0}.hero>p{max-width:540px;line-height:1.7;color:#cbd5e1}.status{display:flex;gap:.5rem;flex-wrap:wrap;margin-top:1.3rem}.status span{font-size:.75rem;color:#94a3b8;border:1px solid rgba(148,163,184,.2);border-radius:999px;padding:.4rem .65rem}.status span.active{color:#d8b4fe;border-color:#a78bfa}.grid{display:grid;grid-template-columns:1fr 1fr;gap:1.2rem}.card{padding:1.6rem;border-radius:22px;background:linear-gradient(145deg,rgba(30,41,59,.85),rgba(15,23,42,.92));border:1px solid rgba(148,163,184,.18)}.card h2{margin:.2rem 0 1.3rem;font-size:1.5rem}.setting{display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:1rem 0;border-top:1px solid rgba(148,163,184,.14)}.setting strong,.choices strong{display:block}.setting span,.data p,.help p{display:block;color:#94a3b8;font-size:.87rem;line-height:1.5;margin-top:.25rem}.setting>button{width:3.1rem;height:1.7rem;border:0;border-radius:999px;background:#334155;padding:.2rem;cursor:pointer;flex:none}.setting>button i{display:block;width:1.3rem;aspect-ratio:1;border-radius:50%;background:#fff;transition:.2s}.setting>button.active{background:#7c3aed}.setting>button.active i{transform:translateX(1.4rem)}.choices{padding-top:1rem;border-top:1px solid rgba(148,163,184,.14)}.choices div{display:flex;gap:.4rem;margin-top:.6rem}.choices button,.data-actions button,.data-actions label,.help a{border:1px solid rgba(148,163,184,.2);border-radius:10px;background:#111827;color:#e2e8f0;padding:.55rem .75rem;text-transform:capitalize;cursor:pointer;text-decoration:none}.choices button.chosen{background:#7c3aed;border-color:#a78bfa}.data p,.help p{font-size:.95rem;margin-bottom:1.2rem}.data-actions{display:flex;gap:.6rem;flex-wrap:wrap}.data-actions label{position:relative}.data-actions input{position:absolute;inset:0;opacity:0;width:100%;cursor:pointer}.data-actions .danger{border-color:#fb7185;color:#fecdd3}.help{background:linear-gradient(135deg,rgba(49,46,129,.48),rgba(8,145,178,.16))}.help a{display:inline-flex;margin-top:.4rem;color:#e9d5ff;border-color:#a78bfa}@media(max-width:760px){.grid{grid-template-columns:1fr}.hero{padding:2rem}.card{padding:1.25rem}}
</style>
