<script lang="ts">
  import exam from '$data/software-engineering/exam-prep.json';
  let current = $state(0); let answer = $state(''); let score = $state(0); let finished = $state(false); let reveal = $state(false);
  const question = () => exam.questions[current];
  function check() { if (!answer) return; reveal = true; }
  function next() { if (answer === question().correctAnswer) score += 1; if (current === exam.questions.length - 1) { finished = true; return; } current += 1; answer = ''; reveal = false; }
  function restart() { current = 0; answer = ''; score = 0; finished = false; reveal = false; }
</script>

<svelte:head><title>Software Engineering Exam Prep · Happy Study</title></svelte:head>

<div class="exam-shell"><section class="hero"><p>SOFTWARE ENGINEERING · EXAM PREP</p><h1>Prove your<br /><em>foundation.</em></h1><span>6-question readiness check</span></section>{#if finished}<section class="result"><p>YOUR SCORE</p><h2>{Math.round(score / exam.questions.length * 100)}%</h2><strong>{score} of {exam.questions.length} correct</strong><p>{score >= 5 ? 'Strong foundation. Move to FreeCodeCamp and build a small project next.' : 'Review the concepts, then try again. Every wrong answer is a useful signal.'}</p><button onclick={restart}>Try again</button><a href="/freecodecamp">Continue with FreeCodeCamp →</a></section>{:else}<section class="quiz"><header><span>QUESTION {current + 1} / {exam.questions.length}</span><div><i style={`width:${(current + 1) / exam.questions.length * 100}%`}></i></div></header><h2>{question().question}</h2><div class="options">{#each question().options as option}<button class:selected={answer === option} class:correct={reveal && option === question().correctAnswer} class:wrong={reveal && answer === option && option !== question().correctAnswer} disabled={reveal} onclick={() => answer = option}>{option}</button>{/each}</div>{#if reveal}<aside><strong>{answer === question().correctAnswer ? 'Correct' : 'Review this one'}</strong><p>{question().explanation}</p></aside>{/if}<footer>{#if reveal}<button onclick={next}>{current === exam.questions.length - 1 ? 'See result' : 'Next question'}</button>{:else}<button disabled={!answer} onclick={check}>Check answer</button>{/if}</footer></section>{/if}</div>

<style>
  .exam-shell{max-width:900px;margin:0 auto;display:grid;gap:1rem}.hero,.quiz,.result{border:1px solid rgba(148,163,184,.18);border-radius:22px;padding:clamp(1.4rem,5vw,3.5rem);background:linear-gradient(145deg,rgba(30,41,59,.82),rgba(15,23,42,.94))}.hero{background:radial-gradient(circle at 80% 20%,rgba(124,58,237,.55),transparent 22rem),linear-gradient(135deg,#111827,#172554)}.hero p,.result>p:first-child{font-size:.7rem;letter-spacing:.14em;font-weight:850;color:#c4b5fd}.hero h1{font-size:clamp(3rem,7vw,5.6rem);line-height:.88;letter-spacing:-.08em;margin:.5rem 0 1rem}.hero em{font:400 1em Georgia,serif;color:#c4b5fd}.hero span{color:#cbd5e1}.quiz header{display:flex;gap:1rem;align-items:center;color:#94a3b8;font-size:.75rem;letter-spacing:.1em}.quiz header div{height:5px;background:#1e293b;flex:1;border-radius:9px;overflow:hidden}.quiz header i{height:100%;display:block;background:#8b5cf6}.quiz h2{font-size:clamp(1.4rem,3vw,2rem);line-height:1.2;margin:2rem 0}.options{display:grid;gap:.65rem}.options button{padding:1rem;border-radius:12px;text-align:left;background:#0b1222;border:1px solid #334155;color:#e2e8f0;cursor:pointer}.options button:hover:not(:disabled),.options button.selected{border-color:#a78bfa;background:rgba(124,58,237,.18)}.options button.correct{border-color:#4ade80;background:rgba(34,197,94,.16)}.options button.wrong{border-color:#fb7185;background:rgba(244,63,94,.14)}.quiz aside{margin-top:1rem;padding:1rem;border-radius:12px;background:rgba(14,116,144,.16);border:1px solid rgba(34,211,238,.2)}.quiz aside strong{color:#67e8f9}.quiz aside p{color:#cbd5e1;margin-bottom:0}.quiz footer{margin-top:1.2rem;display:flex;justify-content:flex-end}.quiz footer button,.result button,.result a{border:0;border-radius:10px;padding:.75rem 1rem;background:#8b5cf6;color:#fff;font-weight:800;text-decoration:none;cursor:pointer}.quiz footer button:disabled{opacity:.45}.result{text-align:center}.result h2{font-size:5rem;margin:.1rem;color:#c4b5fd}.result>p:not(:first-child){color:#cbd5e1;max-width:500px;margin:1rem auto}.result a{display:inline-block;margin-left:.5rem;background:#0e7490}@media(max-width:500px){.result a{display:block;margin:1rem 0 0}}
</style>
